### ISSUE TITLE
Design decision: Vars?

### ISSUE THREAD

**Issue by arrdem** [oxlang/oxlang#11]
Right now var quoting is supported by the grammar but unimplemented in the parser. Pixie and ClojureScript have both implemented vars to some degree, and there is a case to be made that vars are a compile time structure for adding metadata to a symbolic name. Not sure how far I'm willing to let this go, but adding metadata to a named value is definitely useful.

**Comment by mikera** [comment]
FWIW I have come to the conclusion that vars are an implementation detail that provide two things:
- A binding that can be created / mutated / rebound
- A place to store some metadata

Both of these seem relatively orthogonal: I'm thinking that the first is entirely superseded by immutable environments, and the second can be done by allowing metadata to be attached to symbols in immutable environments.
